apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-car
spec:
  template:
    spec:
      containers:
      - name: dummy-car
        image: ghcr.io/tbhuvaneswar/dummy-car:a0faa1c

        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: car-db
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: car-db
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: car-db
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: car-db
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: car-db
                key: DB_PASSWORD
